[project]
name = "gameorganize"
dynamic = ["version"]
dependencies = [
    "pytest", 
    "coverage",
    "flask", 
    "requests",
    "typing_extensions",
    "flask_sqlalchemy"
]
requires-python = ">= 3.8"
